services:
  php-nginx:
    container_name: php-nginx
    image: webdevops/php-nginx:8.2-alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=esphome.*
    volumes:
      - ${NGINX_CONF_FILE}:/opt/docker/etc/nginx/vhost.common.d/10-location-root.conf
      - ${PHP_INDEX_FILE}:/app/index.php
    secrets:
      - .htpasswd
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - VIRTUAL_HOST=dash.esphome.*
  nginxproxy:
    container_name: nginxproxy
    image: nginxproxy/nginx-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock
    restart: unless-stopped
    ports:
      - 80:80
  node:
    container_name: node
    image: node:20-bookworm
    working_dir: /app
    volumes:
      - ../Lockout-V3:/app
      - ${OUTPUT_DIR}:/tmp/lockout-templates
    # environment:
      # - PATH="${PATH}:/root/.local/bin"
    command: >
      sh -c "npm install && node index.js
      --group ${CIVICRM_GROUP_ID}
      --key ${CIVICRM_KEY}
      --apiKey ${CIVICRM_API_KEY}
      --dns ${DNS}
      --subnet ${SUBNET}
      --gateway ${GATEWAY}
      --ip ${IP}
      --wifiPass ${WIFI_PASS}
      --wifiName ${WIFI_NAME}
      --activeTime ${ACTIVE_TIME}
      --pin ${PIN}
      --name ${LOCKOUT_NAME}
      ${INITIAL}
      --output /tmp/lockout-templates"
secrets:
  .htpasswd:
    file: ./.htpasswd